version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=workoutdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  go-app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=workoutdb
      - DB_USER=root
      - DB_PASSWORD=strongpassword
    ports:
      - "8080:8080"

volumes:
  postgres_data: